### ISSUE TITLE
NullPointerException due to the Loading.avatar not being included

### ISSUE THREAD

**Issue by sdkrocks** [vanZeben/BeatSaberOnline#14]
https://github.com/vanZeben/BeatSaberOnline/blob/84a0d31749d4fe2a4f1a3772996948b6977bf84f/BeatSaberOnline/Controllers/AvatarController.cs#L75
Megalon on the beatsaber discord found the issue.

The loading.avatar needs to be included with the mod, otherwise the Online UI option will fail to load

**Comment by vanZeben** [comment]
Added it into the download temporarily @ https://github.com/vanZeben/BeatSaberOnline/releases/tag/v1.0.2

I'll clean this up for the next release

**Comment by sdkrocks** [comment]
> Added it into the download temporarily @ https://github.com/vanZeben/BeatSaberOnline/releases/tag/v1.0.2
> 
> I'll clean this up for the next release

Awesome. Closed caused megalon posted a better explanation of bug
