### ISSUE TITLE
[BUG] MULTIPLAYER button fails to load if the user does not have loading.avatar 

### ISSUE THREAD

**Issue by megalon** [vanZeben/BeatSaberOnline#15]
**Describe the bug**
The `MULTIPLAYER` button fails to load if the user does not have `loading.avatar` in their CustomAvatars folder.
This bug will affect any user that has never had Beat Saber Multiplayer installed, because `loading.avatar` is included in the download for Beat Saber Multiplayer, but not BeatSaberOnline.

**To Reproduce**
1. Install BeatSaberOnline on a system that does not contain `loading.avatar` in the CustomAvatars folder
2. Launch the game
3. The multiplayer button will not appear in the `MODS` menu

**Expected behavior**
The `MULTIPLAYER` button should appear in the menu as usual.

**Logs**
```
  │ 2019-01-30 22:28:00 [Debug] $Active scene changed from "" to "Init"
  │ 2019-01-30 22:28:00 [Debug] $Active scene changed from "Init" to "EmptyTransition"
  │ 2019-01-30 22:28:02 [Debug] $Active scene changed from "EmptyTransition" to "HealthWarning"
  │ 2019-01-30 22:28:17 [Debug] $Active scene changed from "HealthWarning" to "EmptyTransition"
  │ 2019-01-30 22:28:18 [Debug] $Active scene changed from "EmptyTransition" to "Menu"
  │ 2019-01-30 22:28:18 [Debug] $Updating current user info
  │ 2019-01-30 22:28:18 [Error] $Unable to create UI! Exception: System.NullReferenceException: Object reference not set to an instance of an object
  │   at BeatSaberOnline.Controllers.AvatarController.LoadAvatars () [0x00047] in <faac015529da40fbbae5e1b64b14b1a0>:0 
  │   at BeatSaberOnline.Views.PluginUI.CreateUI () [0x00056] in <faac015529da40fbbae5e1b64b14b1a0>:0 
  │ 2019-01-30 22:28:18 [Info] $Found a new version, lets download it https://www.modsaber.org/download/default/beat-saber-online/1.0.1
  │ 2019-01-30 22:29:23 [Debug] $Disconnect from current lobby
  │ 2019-01-30 22:29:23 [Debug] $Sending lobbyId=0,hostname=,status=,joinable=True,UsedSlots=1,TotalSlots=5,MaxSlots=10,CurrentSongId=,CurrentSongDifficulty=0,CurretnSongName=,Screen=NONE,gameplayModifiers={"_energyType":0,"_noFail":false,"_instaFail":false,"_failOnSaberClash":false,"_enabledObstacleType":0,"_noBombs":false,"_fastNotes":false,"_strictAngles":false,"_disappearingArrows":false,"_songSpeed":0}
  │ 2019-01-30 22:29:23 [Debug] $Updating current user info
```

**Additional context**
I believe this is where the error is occuring
https://github.com/vanZeben/BeatSaberOnline/blob/84a0d31749d4fe2a4f1a3772996948b6977bf84f/BeatSaberOnline/Controllers/AvatarController.cs#L75

**Comment by vanZeben** [comment]
Thanks for this, 

Switched the avatar to just use the template one as it's included in CustomAvatars, and rebased the download and changelog of v1.0.2 to use this avatar @ https://github.com/vanZeben/BeatSaberOnline/releases/tag/v1.0.2

 I would prefer to have as little dependencies as possible with this and didn't realize that the loading avatar wasn't included in the default bundle.
