### ISSUE TITLE
[Feature] Indicate in lobby who is host

### ISSUE THREAD

**Issue by megalon** [vanZeben/BeatSaberOnline#23]
**Is your feature request related to a problem? Please describe.**
It would be nice to show in the lobby which user is the host of the room.
This would let everyone know who is selecting the songs.

**Describe the solution you'd like**
When clicking the `MULTIPLAYER` button to view the room selection, you could show the name of the current room you are in (and the username of the host).

**Describe alternatives you've considered**
You could show the text [HOST] next to the users name on the leaderboard.
It would probably need to be a different color so that users can't fake being the host by adding [HOST] to their steam name.

**Comment by lolPants** [comment]
You could make it glow too, like how your own name glows, but with an alternate colour.

**Comment by vanZeben** [comment]
Fixed in https://github.com/vanZeben/BeatSaberOnline/commit/3c5d4c07307bdc4091465e4f62e39e0dce080a50
